### ISSUE TITLE
INHCI input not recognized

### ISSUE THREAD

**Issue by Abdel-youssef** [brsynth/RetroPath2-wrapper#3]
each time I try to run the retropath 2.0 with the acetone INCHI, the job is not executed and I receive an error that the INCHI is not a valid InChI notation. I used the pubchem INCHI and it should be a valid one. "InChI=1S/C3H6O/c1-3(2)4/h1-2H3"

**Comment by tduigou** [comment]
Thanks reporting this. This should be fixed now.
